//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Services = new HashSet<Service>();
            this.ProjectPersons = new HashSet<ProjectPerson>();
            this.Degrees = new HashSet<Degree>();
            this.Conventions = new HashSet<Convention>();
            this.PersonPositions = new HashSet<PersonPosition>();
            this.PersonSkills = new HashSet<PersonSkill>();
            this.Employees = new HashSet<Employee>();
            this.CourseStudents = new HashSet<CourseStudent>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Gsm { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Nationality { get; set; }
        public string Profile { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<ProjectPerson> ProjectPersons { get; set; }
        public virtual ICollection<Degree> Degrees { get; set; }
        public virtual ICollection<Convention> Conventions { get; set; }
        public virtual ICollection<PersonPosition> PersonPositions { get; set; }
        public virtual ICollection<PersonSkill> PersonSkills { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<CourseStudent> CourseStudents { get; set; }
    }
}
