//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSkill
    {
        public int Id { get; set; }
        public string Importance { get; set; }
        public string Level { get; set; }
    
        public Skill Skill { get; set; }
        public Person Person { get; set; }
    }
}
