//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Services = new HashSet<Service>();
            this.Skills = new HashSet<Skill>();
            this.ProjectPositions = new HashSet<ProjectPosition>();
            this.PersonPositions = new HashSet<PersonPosition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<ProjectPosition> ProjectPositions { get; set; }
        public virtual ICollection<PersonPosition> PersonPositions { get; set; }
    }
}
