//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spinn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSkill
    {
        public int Id { get; set; }
        public int Importance { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual ProjectPerson ProjectPerson { get; set; }
    }
}
